### ISSUE TITLE
Discuss about EasyComment and CmsKit.

### ISSUE THREAD

**Issue by gdlcf88** [EasyAbp/EasyComment#5]
Hi @hikalkan, EasyComment is an application module that serves other application modules or apps.

I talked to @wakuflair, we think that CmsKit is a good idea, we believe that the EasyComment can be transferred to the ABP official repo and be transformed and continued to be developed as the implementation of the "comment component".

Here is an introduction to this module:
https://github.com/EasyAbp/EasyComment/blob/develop/README.md

Do you want to pick this module? Please consider it. Thank you.

**Comment by hikalkan** [comment]
Thanks a lot @gdlcf88 for all your efforts on the ABP Framework.

While we can not copy/paste & directly make it working (as you can expect from any code 😄) we will definitely check your source code to get an idea. If our implementation (we may copy some parts from you) satisfies you, then you can drop this work. I also prefer to go with a single source. You can always contribute to the CmsKit once it gets mature.

Thanks.

**Comment by gdlcf88** [comment]
Thank you for your reply. @hikalkan
